"""Added lambda function to timestamp field in RevokedTokenModel

Revision ID: 717f8a38b617
Revises: cc92e98b7efa
Create Date: 2024-09-16 22:44:45.849416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '717f8a38b617'
down_revision: Union[str, None] = 'cc92e98b7efa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
