"""Added unique constraint to name field for TopicModel

Revision ID: a2597c46bb17
Revises: 175e9007e7b3
Create Date: 2024-09-09 22:05:42.428325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2597c46bb17'
down_revision: Union[str, None] = '175e9007e7b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_topics_name', table_name='topics')
    op.create_index(op.f('ix_topics_name'), 'topics', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_topics_name'), table_name='topics')
    op.create_index('ix_topics_name', 'topics', ['name'], unique=False)
    # ### end Alembic commands ###
