"""Added user_id field to RevokedTokenModel

Revision ID: beccebd66ce8
Revises: a2597c46bb17
Create Date: 2024-09-14 14:58:42.401706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beccebd66ce8'
down_revision: Union[str, None] = 'a2597c46bb17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('revoked_tokens', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_revoked_tokens_user_id'), 'revoked_tokens', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_revoked_tokens_user_id'), table_name='revoked_tokens')
    op.drop_column('revoked_tokens', 'user_id')
    # ### end Alembic commands ###
