"""Add question_sets table

Revision ID: 4c57d74754e4
Revises: 3e72983f5a91
Create Date: 2024-03-08 23:18:55.478012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c57d74754e4'
down_revision: Union[str, None] = '3e72983f5a91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_sets_id'), 'question_sets', ['id'], unique=False)
    op.create_index(op.f('ix_question_sets_name'), 'question_sets', ['name'], unique=False)
    op.add_column('questions', sa.Column('question_set_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'questions', 'question_sets', ['question_set_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'questions', type_='foreignkey')
    op.drop_column('questions', 'question_set_id')
    op.drop_index(op.f('ix_question_sets_name'), table_name='question_sets')
    op.drop_index(op.f('ix_question_sets_id'), table_name='question_sets')
    op.drop_table('question_sets')
    # ### end Alembic commands ###
